"""
Redundancy vs. Compounding: Extended Numerical Companion
=========================================================

Tests three competing claims for combined filter+constraint phantoms:
  (T) Trilogy claim: aligned -> super-additive compound (combined > filter + constraint)
  (R) Reformulation v1: aligned -> redundancy (combined < sum); orthogonal -> super-additive
  (R') Reformulation v2: aligned -> most redundancy; anti-aligned -> super-additive
                         (corrected after seeing the data)

Also verifies the Bregman triangle identity for e-projection onto m-flat constraint:
  D(pi_true || pi_filter) = D(pi_true || pi_combined) + D(pi_combined || pi_filter)
                            + cross_term
where cross_term = <eta(pi_true) - eta(pi_combined), theta(pi_combined) - theta(pi_filter)>

For our parameterization (constraint moves along e-geodesic generated by reward r):
  cross_term = lam_combined * (E_{pi_true}[r] - E_{pi_combined}[r])
             = lam_combined * (E_{pi_true}[r] - R_0)
"""
import numpy as np

np.random.seed(42)
N_X, N_Y = 16, 8
reward = (np.arange(N_Y) - (N_Y - 1) / 2) / ((N_Y - 1) / 2)


def make_truth():
    logits = np.zeros((N_X, N_Y))
    for x in range(N_X):
        center = (x / (N_X - 1)) * (N_Y - 1)
        for y in range(N_Y):
            logits[x, y] = -((y - center) ** 2) / 2.0
    logits -= logits.max(axis=1, keepdims=True)
    p = np.exp(logits)
    p /= p.sum(axis=1, keepdims=True)
    return p


pi_true = make_truth()
pi_ref = np.ones((N_X, N_Y)) / N_Y
truth_reward_per_x = pi_true @ reward
truth_overall_reward = truth_reward_per_x.mean()


def e_project(pi_0, reward, R_0, tol=1e-12, max_iter=400):
    def policy_at(lam):
        logits = np.log(pi_0 + 1e-30) + lam * reward[None, :]
        logits -= logits.max(axis=1, keepdims=True)
        p = np.exp(logits)
        p /= p.sum(axis=1, keepdims=True)
        return p

    def avg_reward(lam):
        return policy_at(lam).mean(axis=0) @ reward

    if avg_reward(0) >= R_0:
        return policy_at(0), 0.0
    lo, hi = 0.0, 50.0
    while avg_reward(hi) < R_0:
        hi *= 2
        if hi > 1e10:
            raise ValueError("R_0 unreachable")
    for _ in range(max_iter):
        mid = 0.5 * (lo + hi)
        if avg_reward(mid) < R_0:
            lo = mid
        else:
            hi = mid
        if hi - lo < tol:
            break
    return policy_at(mid), mid


def kl(p, q):
    return (p * (np.log(p + 1e-30) - np.log(q + 1e-30))).sum(axis=1).mean()


def expected_reward(p):
    return p.mean(axis=0) @ reward


# Filter scenarios -----------------------------------------------------------
n_filtered = N_X // 2
idx = np.argsort(truth_reward_per_x)
G_aligned = idx[:n_filtered].tolist()           # filter LOW-reward truth -> push policy reward UP
G_anti = idx[-n_filtered:].tolist()             # filter HIGH-reward truth -> push policy reward DOWN
rng = np.random.default_rng(0)
G_ortho = rng.choice(N_X, n_filtered, replace=False).tolist()


def filter_mask(G):
    m = np.zeros(N_X, dtype=bool)
    m[list(G)] = True
    return m


def m_extend(pi_data_fit, pi_default, mask):
    p = pi_data_fit.copy()
    p[mask] = pi_default[mask]
    return p


# Analysis -------------------------------------------------------------------
def analyze(R_0, name, G):
    mask = filter_mask(G)
    pi_filter = m_extend(pi_true, pi_ref, mask)
    pi_constraint, lam_c = e_project(pi_ref, reward, R_0)
    pi_combined, lam_comb = e_project(pi_filter, reward, R_0)

    D_tf = kl(pi_true, pi_filter)             # filter alone
    D_tc = kl(pi_true, pi_constraint)         # constraint alone
    D_tcomb = kl(pi_true, pi_combined)        # combined
    D_combfilter = kl(pi_combined, pi_filter) # cost of constraint move (after filter)

    R_filter = expected_reward(pi_filter)
    R_true = expected_reward(pi_true)
    cross_term = lam_comb * (R_true - R_0)    # predicted from theory

    # Bregman triangle: D(pi_true || pi_filter) =? D(pi_true || pi_combined)
    #                                            + D(pi_combined || pi_filter) + cross_term
    triangle_lhs = D_tf
    triangle_rhs = D_tcomb + D_combfilter + cross_term
    triangle_residual = triangle_lhs - triangle_rhs

    # Excess of combined over (a) filter alone (b) constraint alone (c) max (d) sum
    return dict(
        name=name,
        R_filter=R_filter,
        lam_combined=lam_comb,
        D_filter=D_tf,
        D_constraint=D_tc,
        D_combined=D_tcomb,
        D_combfilter=D_combfilter,
        sum_individual=D_tf + D_tc,
        max_individual=max(D_tf, D_tc),
        excess_over_max=D_tcomb - max(D_tf, D_tc),
        excess_over_sum=D_tcomb - (D_tf + D_tc),
        cross_term=cross_term,
        triangle_residual=triangle_residual,
    )


print("=" * 85)
print(f"Setup: N_X={N_X}, N_Y={N_Y}, n_filtered={n_filtered}")
print(f"Truth overall reward: {truth_overall_reward:.4f}")
print(f"Truth per-x reward range: [{truth_reward_per_x.min():.3f}, {truth_reward_per_x.max():.3f}]")
print("=" * 85)
print()

scenarios = [("aligned", G_aligned), ("orthogonal", G_ortho), ("anti-aligned", G_anti)]

for R_0 in [0.2, 0.4, 0.6, 0.8]:
    print("-" * 85)
    print(f"R_0 = {R_0}   (constraint {'satisfied' if truth_overall_reward >= R_0 else 'VIOLATED'} by truth)")
    print("-" * 85)
    rows = [analyze(R_0, name, G) for name, G in scenarios]

    # Key comparisons
    print(f"  {'metric':<28s} " + "".join(f"{r['name']:>14s}" for r in rows))
    for key in ["R_filter", "lam_combined", "D_filter", "D_constraint", "D_combined",
                "D_combfilter", "sum_individual", "excess_over_max", "excess_over_sum",
                "cross_term", "triangle_residual"]:
        print(f"  {key:<28s} " + "".join(f"{r[key]:>14.4f}" for r in rows))
    print()

print("=" * 85)
print("Summary across R_0 values: combined phantom relative to baselines")
print("=" * 85)
for R_0 in [0.2, 0.4, 0.6, 0.8]:
    rows = [analyze(R_0, n, G) for n, G in scenarios]
    print(f"R_0={R_0}:")
    for r in rows:
        ratio_max = r["D_combined"] / r["max_individual"]
        ratio_sum = r["D_combined"] / r["sum_individual"]
        sign_m = "+" if r["excess_over_max"] > 0 else "-"
        sign_s = "+" if r["excess_over_sum"] > 0 else "-"
        print(f"  {r['name']:<14s}  D_combined={r['D_combined']:.3f}  "
              f"vs max={r['max_individual']:.3f} ({sign_m}{abs(r['excess_over_max']):.3f}, ratio {ratio_max:.2f}x)  "
              f"vs sum={r['sum_individual']:.3f} ({sign_s}{abs(r['excess_over_sum']):.3f}, ratio {ratio_sum:.2f}x)")
    print()
